/*
https://www.hackerrank.com/challenges/the-report/problem?h_r=next-challenge&h_v=zen
*/

--Solution #1
SELECT CASE
    WHEN GRADE < 8 THEN NULL
    ELSE NAME
END
, GRADE, MARKS
FROM STUDENTS
  JOIN GRADES ON STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND GRADES.MAX_MARK
ORDER BY GRADE DESC, NAME ASC;

--Solution #2
SELECT IF(GRADE < 8, NULL, NAME), GRADE, MARKS
FROM STUDENTS JOIN GRADES
WHERE MARKS BETWEEN MIN_MARK AND MAX_MARK
ORDER BY GRADE DESC, NAME